### ISSUE TITLE
ModuleNotFoundError: No module named 'verifier'

### ISSUE THREAD

**Issue by GregHilston** [Karumi/Kin#33]
```
Traceback (most recent call last):
  File "/Users/ghilston/.virtualenvs/kin/bin/kin", line 7, in <module>
    from kin.kin import main
  File "/Users/ghilston/.virtualenvs/kin/lib/python3.6/site-packages/kin/kin.py", line 5, in <module>
    from verifier import Verifier
ModuleNotFoundError: No module named 'verifier'
```

Unable to get kin to run. I believe the upload to PyPi is botched?

**Comment by Serchinastico** [comment]
Hi,

I think you are using python 3 but I'm afraid we only support python 2.7. Please refer to https://github.com/Karumi/Kin/issues/32

Thanks for reporting!
